name: ci

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

env:
  BINARY: atlas-cli-zig-plugin
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - target: x86_64-macos
            name: atlas-cli-zig-plugin-darwin_amd64.tar.gz
          - target: aarch64-macos
            name: atlas-cli-zig-plugin-darwin_arm64.tar.gz

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - name: Build binary
        run: zig build -Doptimize=ReleaseSmall -Dtarget=${{ matrix.platform.target }}
      - name: Add Version as environment variable
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Add version to manifest file
        run: |
          # interpolate $BINARY, $VERSION, $GITHUB_REPOSITORY_OWNER, $GITHUB_REPOSITORY_NAME
          envsubst < manifest.template.yml > manifest_temp.yml && mv manifest_temp.yml manifest.yml
      - name: Package as archive
        shell: bash
        run: |
          cd zig-out/bin
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
              7z a ../../${{ matrix.platform.name }} $BINARY ../../manifest.yml
          else
              tar czvf ../../${{ matrix.platform.name }} $BINARY -C ../../ manifest.yml
          fi
        if: startsWith( github.ref, 'refs/tags/v' )
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: "atlas-cli-zig-plugin-*"
        if: startsWith( github.ref, 'refs/tags/v' )
